traxiapp/drivers/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField, RadioField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from traxiapp.models import User
from flask_login import current_user

class ReviewForm(FlaskForm):
    rating = RadioField('Rating', choices=[('1','horrible'),('2','awefull'),('3','doable'),('4','good'),('4','excellent')])
    review_text = TextAreaField('Care to expand on that sir?', validators=[DataRequired(), Length(max=300)])
    submit = SubmitField('Submit Review')

traxiapp/users/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, BooleanField, SubmitField, TextAreaField
from wtforms.fields.html5 import EmailField
from wtforms.validators import DataRequired, Length, Email, EqualTo, ValidationError
from flask_wtf.file import FileField, FileAllowed, FileRequired
from traxiapp.models import User, Availability
from flask_login import current_user
from traxiapp import profilepictures


class LoginForm(FlaskForm):
    email = StringField('Email', validators=[DataRequired(), Email()])
    password = PasswordField('Password', validators=[DataRequired()])
    remember_me = BooleanField('Remember Me')
    submit = SubmitField('Login')


class RegisterForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = StringField('Email', validators=[DataRequired(), Email(message='Invalid email'), Length(max=50)])
    password = PasswordField('Password', validators=[DataRequired(), Length(min=6, max=80)])
    confirm_password = PasswordField('Confirm Password', validators=[DataRequired(), EqualTo('password')])
    submit = SubmitField('Sign Up')
    driver_checkbox = BooleanField('Register as driver?')

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user:
            raise ValidationError('That username is taken. Please choose a different one.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user:
            raise ValidationError('That email is taken. Please choose a different one.')

class UpdateAccountForm(FlaskForm):
    username = StringField('Username', validators=[DataRequired(), Length(min=3, max=20)])
    email = EmailField('Email', validators=[DataRequired(), Email(message='Invalid email'), Length(max=50)])
    country = StringField('Country', Length(max=50))
    city = StringField('City', validators=[Length(max=50)])
    country = StringField('Country', validators=[Length(max=50)])
    about = TextAreaField('About')
    submit = SubmitField('Update')
    profile_pic = FileField('Profile picture', validators=[FileAllowed(profilepictures, 'Only images are allowed')])

    def validate_username(self, username):
        user = User.query.filter_by(username=username.data).first()
        if user.username == current_user.username:
            pass
        elif user:
            raise ValidationError('Username exists, please choose another.')

    def validate_email(self, email):
        user = User.query.filter_by(email=email.data).first()
        if user.email == current_user.email:
            pass
        elif user:
            raise ValidationError('Email exists, please choose another.')

traxiapp/drivers/routes.py
from flask import Blueprint, url_for, redirect, render_template, current_app, flash, request
from flask_login import current_user, login_user, logout_user, login_required
from traxiapp import db, bcrypt
from traxiapp.models import User, Role, Review
from traxiapp.drivers.forms import ReviewForm


drivers = Blueprint('drivers', __name__)

# Template filters
@drivers.app_template_filter('datetimeformat')
def datetimeformat(value, format='%d %B %Y'):
    return value.strftime(format)

@drivers.route("/<username>/profile", methods=['GET', 'POST'])
def user(username):
    user=User.query.filter_by(username=username).first()
    reviews=Review.query.filter_by(driver=user.username).all()
    return render_template('profile.html', user=user, title=user.username, reviews=reviews)

@drivers.route("/drivers/<username>/create_review",  methods=['GET', 'POST'])
def create_review(username):
    form = ReviewForm()
    driver=User.query.filter_by(username=username).first()
    user=User.query.filter_by(username=current_user.username).first()
    if form.validate_on_submit():
        current_user.create_review(driver, form.rating.data, form.review_text.data)
        db.session.commit()
        reviews=Review.query.filter_by(driver=driver.username).all()
        return redirect(url_for('drivers.user', username=driver.username, reviews=reviews))
    return render_template('create_review.html', user=driver, form=form, title=driver.username)
    
    

traxiapp/users/routes.py
import os
from pathlib import Path
import glob
from flask import Blueprint, url_for, redirect, render_template, current_app, flash, request
from flask_login import current_user, login_user, logout_user, login_required
from traxiapp import db, bcrypt
from traxiapp.users.forms import LoginForm, RegisterForm, UpdateAccountForm
from traxiapp.models import User, Role, Availability
from traxiapp import profilepictures


users = Blueprint('users', __name__)

# Template filters
@users.app_template_filter('datetimeformat')
def datetimeformat(value, format='%d %B %Y'):
    return value.strftime(format)

# url route for the registration page
@users.route('/register',  methods=['GET', 'POST'])
def register():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    # instantiate the registration form
    form = RegisterForm()
    if form.validate_on_submit():
        hashed_password = bcrypt.generate_password_hash(form.password.data).decode('utf-8')
        new_user = User(username=form.username.data, email=form.email.data, password=hashed_password)
        db.session.add(new_user)
        # create entry in the association (userroles) table according to the value of the checkbos
        if form.driver_checkbox.data is True:
            driver_role = Role.query.filter_by(name='driver').first()
            new_user.roles.append(driver_role)
        else:
            user_role = Role.query.filter_by(name='end-user').first()
            new_user.roles.append(user_role)
        db.session.commit()
        flash(f'{form.username.data} created an account!', 'success')
        return redirect(url_for('users.login'))
    return render_template('register.html', title='Register', form=form)


# url route for the login page
@users.route('/login', methods=['GET', 'POST'])
def login():
    if current_user.is_authenticated:
        return redirect(url_for('main.home'))
    form = LoginForm()
    if form.validate_on_submit():
        user = User.query.filter_by(email=form.email.data).first()
        if user and bcrypt.check_password_hash(user.password, form.password.data):
            login_user(user, remember=form.remember_me.data)
            next_page = request.args.get('next')
            return redirect(next_page) if next_page else redirect(url_for('main.home'))
        else:
            flash('Invalid username or password', 'danger')
            return redirect(url_for('users.login'))
    return render_template('login.html', title='Sign in', form=form)


# url route for the logout page
@users.route('/logout')
def logout():
    logout_user()
    return redirect(url_for('main.home'))

# url route for the account page
@users.route('/<username>/account', methods=['GET', 'POST'])
@login_required
def account(username): 
    form = UpdateAccountForm()
    if request.method== 'POST' and form.validate():
        current_user.username = form.username.data
        current_user.email = form.email.data
        current_user.country = form.country.data
        current_user.city = form.city.data
        current_user.about = form.about.data
        # if a profile picture is uploaded
        if 'profile_pic' in request.files:
            # chekc if user allready has avatar on the filesystem and if yes, remove it 
            basedir = Path(__file__).resolve().parents[1]
            picsdir = 'static/profile_pics'
            filepath = filepath_form = os.path.join(basedir,picsdir)
            filepath_user =  glob.glob('{}/{}_*'.format(filepath,current_user.username))
            filepath_user_string = ''.join(filepath_user)
            if os.path.exists(filepath_user_string):
                os.remove(filepath_user_string)
            # save avatar to filesystem and filename + url to the database
            filename = profilepictures.save(request.files['profile_pic'], name='{}_{}'.format(current_user.username,request.files['profile_pic'].filename))
            url = profilepictures.url(filename)
            current_user.profile_pic_filename = filename
            current_user.profile_pic_url = url
        db.session.commit()
        flash('Your account has been updated', 'success')
        if current_user.has_role('driver'):
            return redirect(url_for('drivers.user', username=current_user.username))
        else:
            return redirect(url_for('main.home'))
    elif request.method== 'POST' and not form.validate():
        return render_template('account.html', title='Account', form=form)
    elif request.method == 'GET':
        form.username.data = current_user.username
        form.email.data = current_user.email
        form.country.data = current_user.country
        form.city.data = current_user.city
        form.about.data = current_user.about
        return render_template('account.html', title='Account', form=form)
    

traxiapp/templates/_driver.html
<article class="media box has-background-light">
    <figure class="media-left">
        <div class="avatar-cropper">
            <img class='avatar' onerror="this.src='/static/images/blank-profile-picture.png';" src="/static/profile_pics/{{ driver.profile_pic_filename }}">
        </div>
    </figure>
    <div class="media-content">
        <div class="content">
            <a href="{{ url_for('drivers.user', username=driver.username) }}" id="link-{{  driver.username  }}"><strong>
                    {{ driver.username }}</strong></a>
            <p><strong>{{ driver.country }}</strong> {{ driver.city }}<br>
                {{ driver.about }}</p>
        </div>
    </div>
</article>

traxiapp/templates/_review.html
<article class="media">
        <div class="media-content">
                <div class="content">
                    <p>
                        <strong>{{ review.user }}</strong> <small>{{ review.created|datetimeformat }}</small><br>
                        {{ review.review_text }}
                    </p>
                </div>
        </div>
</article>

traxiapp/templates/about.html
{% extends "base.html" %}

{% block content %}
<section class='section'>
    <div class='container box has-background-light'>
        <h1 class='title has-text-centered'>About Us</h1>
        <p>We – Afke, Chris, Elma & Wouter – realized that the most important thing while travelling are the people you
            travel with. You can easily choose friends or family to bring along, but sometimes it’s not that easy to
            find that person who ensures you are safe, that person who teaches you about local culture and customs,
            that person who can make or break a trip: your driver.
            With Traxiworld, we offer a way for everyone who is looking for a great holiday to find the best driver: we
            have selected the finest of Uganda. For drivers, Traxiworld is a new way to advertise their services
            directly to potential customers, and, by cutting out the middle-man, providing them with higher earnings.
        </p>
    </div>
    <div class='container box has-background-light'>
        <h1 class='title has-text-centered'>Our Mission</h1>
        <p>
            Traxiworld connects tourists and drivers in Uganda. Our aim is to set an example in the gig economy as a
            platform that doesn’t just connect people, but also ensures that both parties are better off. We guarantee
            a care-free, fun trip for the tourist; and a competitive rate for the driver.
        </p>
    </div>
</section>

{% endblock %}

traxiapp/templates/account.html
{% extends "base.html" %}

{% block content %}
<div class="tile is-ancestor">
    <div class='tile is-9 is-parent'>
        <div class='is-tile is-child'>
            <h1>Update Profile Information</h1>
            <br>

            <form method="POST" action='' enctype="multipart/form-data">
                {{ form.hidden_tag() }}
                <div class='field'>
                    <label class='label'>Username</label>
                    <div class='control' style='width: 300px'>
                        {{ form.username(class='input') }}
                        {% for error in form.username.errors %}
                        <p class='has-text-danger'>{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class='field'>
                    <label class='label'>Email</label>
                    <div class='control' style='width: 300px'>
                        {{ form.email(class='input') }}
                        {% for error in form.email.errors %}
                        <p class='has-text-danger'>{{ error }}</p>
                        {% endfor %}
                    </div>
                </div>
                <div class='field'>
                    <label class='label'>Country</label>
                    <div class='control' style='width: 300px'>
                        {{ form.country(class='input') }}
                    </div>
                </div>
                <div class='field'>
                    <label class='label'>City</label>
                    <div class='control' style='width: 300px'>
                        {{ form.city(class='input') }}
                    </div>
                </div>
                <div class='field'>
                    <label class='label'>About</label>
                    <div class='control' style='width: 300px'>
                        {{ form.about(class='input') }}
                    </div>
                </div>
                <br>
                <div class='field'>
                    <label class='label'>Avatar</label>
                    <div class='control' style='width: 300px'>
                        <input class='inputfile' type='file' name='profile_pic' id='profile_pic' />
                        <label class='button' for="profile_pic">Select picture...</label>
                        <input class='input' type="text" name="file" id="filename" readonly>
                    </div>
                </div>
                <br>

                {{ form.submit(class='button is-warning') }}

        </div>
        </form>
    </div>
</div>
</div>
<script type='text/javascript' src='/static/js/filename.js'></script>

{% endblock content %}

traxiapp/templates/base.html
<!doctype html>
<html lang="en" class="has-navbar-fixed-top">

<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- , shrink-to-fit=no -->

    <!-- Traxi_CSS - SASS generated -->
    <link rel="stylesheet" type="text/css" href="/static/css/traxi.css">
    <link rel="stylesheet" type="text/css" href="/static/css/inputfile.css">
    <link rel="stylesheet" href="//code.jquery.com/ui/1.12.1/themes/base/jquery-ui.css">

    <!--JQuery-->
    <script src="/static/js/jquery-3.3.1.min.js"></script>
    <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>

    {% if title %}
    <title>Traxi - {{ title }}</title>
    {% else %}
    <title>Traxi</title>
    {% endif %}
</head>

<body>

    <nav class="navbar is-fixed-top">
        <div class="container">
            <div class="navbar-brand">
                <a class="navbar-item" href="/"><strong>Traxi</strong></a>
                <a role="button" class="navbar-burger burger" aria-label="menu" aria-expanded="false" data-target="navbarBasic">
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                    <span aria-hidden="true"></span>
                </a>
            </div>
            <div id="navbarBasic" class="navbar-menu">
                <div class="navbar-start">
                    <a class="navbar-item" href='/home'>How it Works</a>
                    <a class="navbar-item" href='/about'>About Us</a>
                </div>
                <div class="navbar-end">
                    {% if current_user.is_authenticated %}
                    <a class="navbar-item" href="{{ url_for('users.account', username=current_user.username) }}"">Account</a>
                    <a class="navbar-item" href='/logout'>Logout</a>

                    {% else %}
                    <a class="navbar-item" href='/login'>Login</a>
                    <a class="navbar-item" href='/register'>Register</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </nav>
    <script>
        document.addEventListener('DOMContentLoaded', () => {

            // Get all "navbar-burger" elements
            const $navbarBurgers = Array.prototype.slice.call(document.querySelectorAll('.navbar-burger'), 0);

            // Check if there are any navbar burgers
            if ($navbarBurgers.length > 0) {

                // Add a click event on each of them
                $navbarBurgers.forEach(el => {
                    el.addEventListener('click', () => {

                        // Get the target from the "data-target" attribute
                        const target = el.dataset.target;
                        const $target = document.getElementById(target);

                        // Toggle the "is-active" class on both the "navbar-burger" and the "navbar-menu"
                        el.classList.toggle('is-active');
                        $target.classList.toggle('is-active');

                    });
                });
            }

        });
    </script>

        {% with messages = get_flashed_messages() %}
        {% if messages %}
        <ul class='container'>
            {% for message in messages %}
            <li>{{ message }}</li>
            {% endfor %}
        </ul>
        {% endif %}
        {% endwith %}

    <div class="container">
        {% block content %}{% endblock content %}
    </div>

    <footer class="footer">
        <div class="content has-text-centered">
            <p>
                Niet zo <a href="/static/images/ikea_dontbeaglum.png">janken</a>. <strong>Kut.</strong>
            </p>
        </div>
    </footer>
</body>

</html>

traxiapp/templates/create_review.html
{% extends "base.html" %}
{% block content %}

 
  <section class="section">
      <form method="POST" action="">
          {{ form.hidden_tag() }}
  <div class="box">
  <div class="field is-horizontal">
      <div class="field-label">
        <label class="label">Reet your experience !!!</label>
      </div>
      <div class="field-body">
        <div class="field is-narrow">
          <div class="control">
            {{ form.rating }}
            </label>
          </div>
        </div>
      </div>
    </div>
    <div class="field is-horizontal">
      <div class="field-label">
          {{ form.review_text.label(class="label") }}
      </div>
      <div class="field-body">
          {{ form.review_text }}
      </div>
    </div>
    <div class="field-body">
    {{ form.submit(class="button is-dark") }}
  </div>
  </div>
</form>
  </section>

 


{% endblock content %}

traxiapp/templates/home.html
{% extends "base.html" %}

{% block content %}
<section class="hero is-primary is-medium has-bg-img">
    <div class="hero-body">
        <div class="container">
            <h1 class="title is-1 has-indent-1">
                traxiworld
            </h1>
            <h2 class="subtitle has-indent-2">
                find your personal driver
            </h2>
        </div>
    </div>
</section>
<!--<br>-->
<p class="is-size-7 has-text-right"><a href="https://github.com/traxibv/master_traxi/branches">branch:</a><strong>
        billyproof</strong></p>
<div class="box is-hidden-mobile has-background-light">
    <section class="tile is-ancestor is-flex">
        <div class="tile is-parent is-vertical">
            <div class="tile is-child p-icon">
                <i class="icon-055 icon-bg has-indent-1"></i>
                <p class="has-text-weight-bold p-icon">Reliable</p>
                <p class="p-icon">All our drivers are certified and are very experienced.</p>
            </div>
        </div>
        <div class="tile is-parent is-vertical">
            <div class="tile is-child p-icon">
                <i class="icon-268 icon-bg has-indent-1"></i>
                <p class="has-text-weight-bold p-icon">Easy</p>
                <p class="p-icon">Just search, contact and book.</p>
            </div>
        </div>
        <div class="tile is-parent is-vertical">
            <div class="tile is-child p-icon">
                <i class="icon-008 icon-bg has-indent-1"></i>
                <p class="has-text-weight-bold p-icon">Fair</p>
                <p class=" p-icon">Max-Havelaar drivers are the new chocolate.</p>
            </div>
        </div>
    </section>
</div>
<div class="is-small-pad is-hidden-tablet p-icon">
    <i class="icon-bgs has-indent-1"></i>
    <p class="has-text-weight-bold is-size-7 p-icon">Reliable, Easy, Fair<p>
            <p class="is-size-7 p-icon">All our drivers are certified and are very experienced. Just search, contact
                and book. Max-Havelaar drivers are the new chocolate.<p>
</div>

<h1 class='title has-text-centered'>Find your driver</h1>


<div class="tile is-ancestor">
    <div class="tile is-parent is-vertical">
        {% for driver in drivers %}
        <div class="tile is-child">
            {% include '_driver.html' %}
        </div>
        {% endfor %}
    </div>
</div>


<script>
    $('#startdate').datepicker();
    $('#enddate').datepicker(); 
</script>

{% endblock content %}

traxiapp/templates/index.html
<!doctype html>
<html>

<head>
<style>
    div {margin-left:50px; font: 11px monospace;}
    iframe {
       display:block;
       margin-left: 50px;
       width:600px;
       height:94vh;
    }
</style>
</head>

<body>
    <div>@index.html edit ip to local/network flask_server address. For Dev1 use: http://62.58.236.196:9000/</div>
    <iframe src="http://192.168.1.200:5000/home" frameborder="1"></iframe>

</body>
</html>

traxiapp/templates/login.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="col-md-6">
            <legend>Sign In</legend>

            <div class="form-group">
                {{ form.email(class="from-control form-control-lg", placeholder="Email", tabindex="3") }}
            </div>
            <div class="form-group">
                {{ form.password(class="from-control form-control-lg", placeholder="Password", tabindex="3") }}
            </div>
            <div class="form-group">
                {{ form.remember_me() }} {{ form.remember_me.label }}
            </div>

        </fieldset>
        <div class="form-group" style="display: inline">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>

        <!--Invalid username or password-->
        {% with messages = get_flashed_messages(with_categories=true) %}
            {% if messages %}
                {% for category, message in messages %}
                    <small class="alert alert-{{ category }}" style="display: inline">
                        {{ message }}
                    </small>
                {% endfor %}
            {% endif %}
        {% endwith %}

    </form>

    <small class="text-muted">
        Don't Have An Account?<a class="ml-2" href="{{ url_for('users.register') }}">Sign Up</a>
    </small>
</div>
{% endblock %}

traxiapp/templates/profile.html
{% extends "base.html" %}

{% block content %}
<div class='hero'>
  <div class='hero-body'>
    <div class='container'>
      <h1 class="title has-text-centered">Hi, I am {{user.username}}.</h1>
      <h2 class="subtitle has-text-centered">Welcome to my profile!</h2>
    </div>
  </div>
</div>

<section class='section'>
  <figure class="avatar-cropper is-128x128 container">
    <img class='avatar' onerror="this.src='/static/images/blank-profile-picture.png';" src="/static/profile_pics/{{ user.profile_pic_filename }}">
  </figure>
</section>

<section class="tile is-ancestor is-flex">
  <div class="tile is-parent is-vertical">

    <div class='tile is-child box has-background-light'>
      <h2 class="subtitle has-text-centered has-text-weight-bold">About me</h2>
      <p>{{ user.about }}</p>
    </div>
    
    <div class='tile is-child box has-background-light'>
      <h2 class='subtitle has-text-centered has-text-weight-bold'>Reviews</h2>
      {% for review in reviews %}
      {% include '_review.html' %}
      {% endfor %}
      <br>
      <div class='container'>
        {% if current_user.is_authenticated and current_user.has_role('end-user') %}
        <a class="button" href="{{ url_for('drivers.create_review', username=user.username) }}">Create Review</a>
        {% endif %}
      </div>
    </div>

  <div class='tile is-child box has-background-light'>
      <h2 class='subtitle has-text-centered has-text-weight-bold'>Contact</h2>
      <a class='button' href='#'>Send a Message</a>
  </div>
  </div>
</section>

{% endblock %}

traxiapp/templates/register.html
{% extends "base.html" %}
{% block content %}
<div class="container-fluid">
    <form method="POST" action="">
        {{ form.hidden_tag() }}
        <fieldset class="col-md-6">
            <legend>Create an Account</legend>
            <div class="form-group">
                {% if form.username.errors %}
                    {{ form.username(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.username.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.username(class="from-control form-control-lg", placeholder="Username", tabindex="3") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.email.errors %}
                    {{ form.email(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.email.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.email(class="from-control form-control-lg", placeholder="E-Mail", tabindex="3") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.password.errors %}
                    {{ form.password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.password(class="from-control form-control-lg", placeholder="Password", tabindex="3") }}
                {% endif %}
            </div>
            <div class="form-group">
                {% if form.confirm_password.errors %}
                    {{ form.confirm_password(class="form-control form-control-lg is-invalid") }}
                    <div class="invalid-feedback">
                        {% for error in form.confirm_password.errors %}
                            <span>{{ error }}</span>
                        {% endfor %}
                    </div>
                {% else %}
                    {{ form.confirm_password(class="from-control form-control-lg", placeholder="Confirm Password", tabindex="3") }}
                {% endif %}
            </div>
            <div class="form-group">
                {{ form.driver_checkbox() }} {{ form.driver_checkbox.label }}
            </div>
        </fieldset>
        <div class="form-group">
            {{ form.submit(class="btn btn-outline-info") }}
        </div>
    </form>
    <small class="text-muted">
        Allready Have An Account?<a class="ml-2" href="{{ url_for('users.login') }}">Sign In</a>
    </small>
</div>
{% endblock %}

traxiapp/templates/user.html
{% extends "base.html" %}

{% block content %}
<section class="section">
        <div class="container">
          <h1 class="title">Hi, I am {{user.username}}.</h1>
          <h2 class="subtitle">
            Welcome to my profile!
          </h2>
        </div>
      </section>
      <section class="section">
            <div class="box">
          <h2 class="subtitle">Something little about me !!</h2>
          <p>{{ user.about }}</p>
          </div>
      </section>

      <section class="section">
          <div class="box">
          <h2 class="subtitle">General info:</h2>
          <table class="table">
              <tbody>
                  <tr>
                  <th>Username:</th>
                  <td>{{ user.username }}</td>
                  </tr>
                  <tr>
                  <th>Email:</th>
                  <td>{{ user.email }}</td>
                  </tr>
                  <th>Country:</th>
                  <td>{{ user.country }}</td>
                  <tr>
                  <th>City:</th>
                  <td>{{ user.city }}</td>
                  </tr>
              </tbody>
          </table>
        </div>
      </section>

      <section class="section">
          <div class="box">
            <h2 class="subtitle">Reviews</h2>
            {% for review in reviews %}
            <div class="container is-fluid">
                    <div class="box">
                        {% include '_review.html' %}
                    </div>
            </div>
            {% endfor %}
            


            {% if current_user.is_authenticated %}  
            {% if current_user.has_role('end-user') %}
      <a class="button is-dark" href="{{ url_for('drivers.create_review', username=user.username) }}">Create Review</a>
      {% endif %}
      {% endif %}
    </div>
</section>

{% endblock %}